import 'package:hive_flutter/hive_flutter.dart';
import '../../data/models/transaction_model.dart';
import '../../data/models/budget_model.dart';
import '../../data/models/user_settings_model.dart';

class StorageService {
  static const String transactionsBox = 'transactions';
  static const String budgetsBox = 'budgets';
  static const String settingsBox = 'settings';

  // Initialize Hive and register adapters
  static Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    // Uncomment after running: flutter pub run build_runner build
    Hive.registerAdapter(TransactionModelAdapter());
    Hive.registerAdapter(TransactionTypeAdapter());
    Hive.registerAdapter(BudgetModelAdapter());
    Hive.registerAdapter(BudgetPeriodAdapter());
    Hive.registerAdapter(UserSettingsModelAdapter());
    Hive.registerAdapter(ThemeModeAdapter());

    // Open boxes - using dynamic type for now
    await Hive.openBox<TransactionModel>(transactionsBox);
    await Hive.openBox<BudgetModel>(budgetsBox);
    await Hive.openBox<UserSettingsModel>(settingsBox);
  }

  // Get box
  static Box<T> getBox<T>(String boxName) {
    return Hive.box<T>(boxName);
  }

  // Transactions
  static Box<TransactionModel> get transactions =>
      Hive.box<TransactionModel>(transactionsBox);

  // Budgets
  static Box<BudgetModel> get budgets => Hive.box<BudgetModel>(budgetsBox);

  // Settings
  static Box<UserSettingsModel> get settings =>
      Hive.box<UserSettingsModel>(settingsBox);

  // Clear all data
  static Future<void> clearAll() async {
    await transactions.clear();
    await budgets.clear();
  }

  // Close all boxes
  static Future<void> close() async {
    await Hive.close();
  }
}
